import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import test from 'node:test';

const migrationPath =
  'src/infrastructure/database/migrations/20260725183832_database_create_tenants_and_branches.ts';

test('initial schema registry has exact owners, keys and physical scope', async () => {
  const policy = JSON.parse(
    await readFile('architecture/dec-005-policy.json', 'utf8'),
  );
  assert.equal(policy.persistence.status, 'tenant-schema-materialized');
  assert.deepEqual(policy.persistence.databaseObjects, {
    catalog_categories: { owner: 'catalog', kind: 'table' },
    catalog_brands: { owner: 'catalog', kind: 'table' },
    catalog_items: { owner: 'catalog', kind: 'table' },
    catalog_item_identifiers: { owner: 'catalog', kind: 'table' },
    catalog_sku_sequences: { owner: 'catalog', kind: 'table' },
    catalog_category_kind_applicability: { owner: 'catalog', kind: 'table' },
    catalog_brand_kind_applicability: { owner: 'catalog', kind: 'table' },
    catalog_category_pending_values: { owner: 'catalog', kind: 'table' },
    catalog_brand_pending_values: { owner: 'catalog', kind: 'table' },
    catalog_brand_pending_kind_applicability: {
      owner: 'catalog',
      kind: 'table',
    },
    catalog_barcode_sequences: { owner: 'catalog', kind: 'table' },
    catalog_base_price_revisions: { owner: 'catalog', kind: 'table' },
    catalog_branch_price_revisions: { owner: 'catalog', kind: 'table' },
    catalog_reference_cost_revisions: { owner: 'catalog', kind: 'table' },
    catalog_commands: { owner: 'catalog', kind: 'table' },
    catalog_audit_events: { owner: 'catalog', kind: 'table' },
    catalog_reference_deletion_events: { owner: 'catalog', kind: 'table' },
    catalog_reference_identity_locks: { owner: 'catalog', kind: 'table' },
    catalog_reference_merge_events: { owner: 'catalog', kind: 'table' },
    catalog_supplier_sources: { owner: 'catalog', kind: 'table' },
    catalog_supplier_catalog_versions: { owner: 'catalog', kind: 'table' },
    catalog_supplier_version_raw_payloads: { owner: 'catalog', kind: 'table' },
    catalog_supplier_listings: { owner: 'catalog', kind: 'table' },
    catalog_update_batches: { owner: 'catalog', kind: 'table' },
    catalog_update_row_decisions: { owner: 'catalog', kind: 'table' },
    catalog_supplier_listing_resolutions: { owner: 'catalog', kind: 'table' },
    catalog_supplier_reconciliation_memory: { owner: 'catalog', kind: 'table' },
    catalog_supplier_source_deletion_events: { owner: 'catalog', kind: 'table' },
    catalog_retirement_plans: { owner: 'catalog', kind: 'table' },
    catalog_retirement_events: { owner: 'catalog', kind: 'table' },
    catalog_field_policy_heads: { owner: 'catalog', kind: 'table' },
    catalog_field_policy_versions: { owner: 'catalog', kind: 'table' },
    branches: { owner: 'stations', kind: 'table' },
    branch_commands: { owner: 'stations', kind: 'table' },
    branch_audit_events: { owner: 'stations', kind: 'table' },
    tenant_lifecycle_events: { owner: 'tenancy', kind: 'table' },
    stations: { owner: 'stations', kind: 'table' },
    station_bindings: { owner: 'stations', kind: 'table' },
    station_credentials: { owner: 'stations', kind: 'table' },
    repairs: { owner: 'repairs', kind: 'table' },
    customers: { owner: 'customers', kind: 'table' },
    customer_contact_phones: { owner: 'customers', kind: 'table' },
    repair_create_commands: { owner: 'repairs', kind: 'table' },
    repair_folio_sequences: { owner: 'repairs', kind: 'table' },
    repair_intakes: { owner: 'repairs', kind: 'table' },
    repair_equipment_corrections: { owner: 'repairs', kind: 'table' },
    repair_device_types: { owner: 'repairs', kind: 'table' },
    repair_device_type_pending_values: { owner: 'repairs', kind: 'table' },
    repair_device_type_catalog_events: { owner: 'repairs', kind: 'table' },
    repair_brands: { owner: 'repairs', kind: 'table' },
    repair_brand_pending_values: { owner: 'repairs', kind: 'table' },
    repair_brand_catalog_events: { owner: 'repairs', kind: 'table' },
    repair_models: { owner: 'repairs', kind: 'table' },
    repair_model_pending_values: { owner: 'repairs', kind: 'table' },
    repair_model_catalog_events: { owner: 'repairs', kind: 'table' },
    repair_risks: { owner: 'repairs', kind: 'table' },
    repair_intervention_risks: { owner: 'repairs', kind: 'table' },
    repair_risk_catalog_events: { owner: 'repairs', kind: 'table' },
    repair_problem_categories: { owner: 'repairs', kind: 'table' },
    repair_problem_pending_values: { owner: 'repairs', kind: 'table' },
    repair_problem_category_catalog_events: { owner: 'repairs', kind: 'table' },
    repair_problem_category_deletion_events: { owner: 'repairs', kind: 'table' },
    repair_catalog_reference_deletion_events: { owner: 'repairs', kind: 'table' },
    repair_problem_classifications: { owner: 'repairs', kind: 'table' },
    repair_problem_classification_events: { owner: 'repairs', kind: 'table' },
    repair_new_repair_policy_heads: { owner: 'repairs', kind: 'table' },
    repair_new_repair_policy_versions: { owner: 'repairs', kind: 'table' },
    repair_timeline_entries: { owner: 'repairs', kind: 'table' },
    repair_business_audit_events: { owner: 'repairs', kind: 'table' },
    repair_operational_note_request_guards: {
      owner: 'repairs',
      kind: 'table',
    },
    repair_attachments: { owner: 'repairs', kind: 'table' },
    repair_technicians: { owner: 'repairs', kind: 'table' },
    repair_technician_branches: { owner: 'repairs', kind: 'table' },
    repair_technician_assignments: { owner: 'repairs', kind: 'table' },
    repair_workflow_transitions: { owner: 'repairs', kind: 'table' },
    repair_locations: { owner: 'repairs', kind: 'table' },
    repair_location_movements: { owner: 'repairs', kind: 'table' },
    tenants: { owner: 'tenancy', kind: 'table' },
    tenant_bootstrap_commands: { owner: 'tenancy', kind: 'table' },
    tenant_bootstrap_guards: { owner: 'tenancy', kind: 'table' },
    users: { owner: 'users', kind: 'table' },
    user_preferences: { owner: 'users', kind: 'table' },
    user_provisioning_bootstraps: { owner: 'users', kind: 'table' },
    user_lifecycle_commands: { owner: 'users', kind: 'table' },
    user_profile_update_commands: { owner: 'users', kind: 'table' },
    user_create_commands: { owner: 'users', kind: 'table' },
    access_capabilities: { owner: 'access', kind: 'table' },
    access_roles: { owner: 'access', kind: 'table' },
    access_role_capabilities: { owner: 'access', kind: 'table' },
    access_role_assignments: { owner: 'access', kind: 'table' },
    access_role_assignment_commands: { owner: 'access', kind: 'table' },
    access_role_commands: { owner: 'access', kind: 'table' },
    access_pin_credentials: { owner: 'access', kind: 'table' },
    access_pin_credential_commands: { owner: 'access', kind: 'table' },
    access_pin_eligibility_tenant_guards: {
      owner: 'access',
      kind: 'table',
    },
    access_pin_attempt_station_guards: { owner: 'access', kind: 'table' },
    access_pin_attempt_limits: { owner: 'access', kind: 'table' },
    access_operational_session_station_guards: {
      owner: 'access',
      kind: 'table',
    },
    access_operational_sessions: { owner: 'access', kind: 'table' },
    access_admin_auth_attempt_limits: { owner: 'access', kind: 'table' },
    access_admin_identities: { owner: 'access', kind: 'table' },
    access_admin_invitations: { owner: 'access', kind: 'table' },
    access_admin_invitation_grants: { owner: 'access', kind: 'table' },
    access_admin_invitation_challenges: { owner: 'access', kind: 'table' },
    access_admin_invitation_dispatches: { owner: 'access', kind: 'table' },
    access_admin_invitation_commands: { owner: 'access', kind: 'table' },
    access_admin_lifecycle_events: { owner: 'access', kind: 'table' },
    access_admin_password_credentials: { owner: 'access', kind: 'table' },
    access_admin_recovery_challenges: { owner: 'access', kind: 'table' },
    access_admin_security_events: { owner: 'access', kind: 'table' },
    access_admin_sessions: { owner: 'access', kind: 'table' },
    registration_acceptance_documents: { owner: 'registration', kind: 'table' },
    registration_attempts: { owner: 'registration', kind: 'table' },
    registration_email_dispatches: { owner: 'registration', kind: 'table' },
    registration_public_action_limits: { owner: 'registration', kind: 'table' },
    registration_security_events: { owner: 'registration', kind: 'table' },
    registration_verification_challenges: { owner: 'registration', kind: 'table' },
  });
  assert.deepEqual(policy.persistence.initialSchema, {
    migration: migrationPath,
    tables: ['tenants', 'branches'],
    tenantColumns: ['tenant_id', 'created_at'],
    branchColumns: ['tenant_id', 'branch_id', 'created_at'],
    columnTypes: {
      tenant_id: 'uuid',
      branch_id: 'uuid',
      created_at: 'timestamptz',
    },
    tenantPrimaryKeyName: 'tenants_pk',
    tenantPrimaryKey: ['tenant_id'],
    branchPrimaryKeyName: 'branches_pk',
    branchPrimaryKey: ['tenant_id', 'branch_id'],
    branchTenantForeignKey: {
      name: 'branches_tenant_fk',
      columns: ['tenant_id'],
      targetTable: 'tenants',
      targetColumns: ['tenant_id'],
      onUpdate: 'restrict',
      onDelete: 'restrict',
    },
    status: 'tenant-schema-materialized',
  });
  assert.equal(
    policy.persistence.infrastructureFiles[
      'src/infrastructure/database/database-types.ts'
    ].status,
    'materialized-schema-contract',
  );
});

test('productive migration root remains exact and governed', async () => {
  assert.deepEqual(
    await readdir('src/infrastructure/database/migrations'),
    [
      migrationPath.split('/').at(-1),
      '20260819120000_database_create_repairs_worklist.ts',
      '20260819130000_repairs_create_intakes.ts',
      '20260819140000_repairs_create_timeline_entries.ts',
      '20260819150000_repairs_create_attachments.ts',
      '20260820090000_repairs_add_operational_note_idempotency.ts',
      '20260902090000_repairs_create_technician_assignment.ts',
      '20260902093000_repairs_add_technician_unassignment_idempotency.ts',
      '20260902100000_repairs_enforce_technician_scope.ts',
      '20260903120000_repairs_create_workflow_transitions.ts',
      '20260903130000_repairs_create_location_movements.ts',
      '20260904120000_stations_add_branch_timezone.ts',
      '20260905160000_stations_create_trusted_runtime_context.ts',
      '20260906170000_users_create_directory.ts',
      '20260906171000_users_create_provisioning_bootstraps.ts',
      '20260906172000_users_create_lifecycle_commands.ts',
      '20260906180000_access_create_capability_catalog.ts',
      '20260906181000_access_create_roles.ts',
      '20260906182000_access_create_role_assignments.ts',
      '20260907010000_access_create_pin_credentials.ts',
      '20260907110000_stations_add_admission_revisions.ts',
      '20260907111000_users_add_admission_revision.ts',
      '20260907120000_access_create_operational_sessions.ts',
      '20260907220000_repairs_create_business_audit_events.ts',
      '20260907230000_access_add_local_administration_capabilities.ts',
      '20260908000000_access_harden_pin_only_lookup.ts',
      '20260908001000_repairs_create_operational_note_request_guards.ts',
      '20260908002000_access_add_role_editing_commands.ts',
      '20260908010000_access_narrow_pin_eligibility_triggers.ts',
      '20260908020000_users_create_profile_update_commands.ts',
      '20260908021000_users_create_commands.ts',
      '20260908110000_access_add_repairs_create_capability.ts',
      '20260908111000_customers_create_branch_minimum.ts',
      '20260908112000_repairs_enable_minimum_intake_creation.ts',
      '20260908113000_repairs_expand_classic_intake.ts',
      '20260908114000_repairs_expand_avicell_reception.ts',
      '20260908115000_access_add_repairs_configuration_capabilities.ts',
      '20260908120000_repairs_create_new_repair_field_policies.ts',
      '20260908121000_access_add_repairs_catalog_capabilities.ts',
      '20260908122000_repairs_create_risk_catalog.ts',
      '20260908123000_repairs_create_brand_catalog.ts',
      '20260908124000_repairs_create_model_catalog.ts',
      '20260908125000_repairs_enforce_model_brand_compatibility.ts',
      '20260908125100_access_add_repairs_correct_intake_capability.ts',
      '20260908125200_repairs_create_equipment_corrections.ts',
      '20260908130000_access_add_repairs_classify_capability.ts',
      '20260908130100_repairs_create_problem_category_catalog.ts',
      '20260908131000_repairs_add_problem_capture_reconciliation.ts',
      '20260909100000_repairs_add_problem_category_safe_delete.ts',
      '20260909220000_users_create_preferences.ts',
      '20260910230000_repairs_create_device_type_catalog.ts',
      '20260912180000_access_enable_concurrent_operational_sessions.ts',
      '20260912190000_tenancy_add_operating_currency.ts',
      '20260912191000_access_add_catalog_capabilities.ts',
      '20260912192000_users_add_price_list_cost_preference.ts',
      '20260912193000_catalog_create_pricing_core.ts',
      '20260912200000_catalog_add_reference_governance.ts',
      '20260912210000_catalog_unify_pending_reference_reconciliation.ts',
      '20260913120000_catalog_add_reference_safe_delete.ts',
      '20260913121000_repairs_add_reference_safe_delete.ts',
      '20260913130000_catalog_enforce_reference_identity.ts',
      '20260913140000_catalog_add_canonical_reference_merge.ts',
      '20260914150000_catalog_create_bulk_composer.ts',
      '20260914151000_catalog_strengthen_supplier_history.ts',
      '20260914152000_access_add_catalog_bulk_retire_capability.ts',
      '20260914153000_catalog_create_retirement_plans.ts',
      '20260914154000_catalog_add_historical_reactivation.ts',
      '20260914155000_catalog_govern_supplier_history.ts',
      '20260914155100_access_add_supplier_delete_capability.ts',
      '20260915120000_catalog_add_bounded_candidate_matching.ts',
      '20260915130000_catalog_add_supplier_observed_title_history.ts',
      '20260916180000_catalog_add_supplier_version_completeness.ts',
      '20260917190000_catalog_create_field_policies.ts',
      '20260917190100_access_add_catalog_configuration_capabilities.ts',
      '20260917190200_access_add_granular_catalog_capabilities.ts',
      '20260920180000_access_create_admin_identity_sessions.ts',
      '20260921120000_tenancy_create_bootstrap_foundation.ts',
      '20260921121000_access_create_starter_tenant_admin_policy.ts',
      '20260921122000_tenancy_create_bootstrap_guards.ts',
      '20260921150000_registration_create_public_verification.ts',
      '20260921151000_registration_enable_retention_cleanup.ts',
      '20260921160000_stations_materialize_branch_management.ts',
      '20260921161000_tenancy_create_lifecycle_events.ts',
      '20260921162000_stations_extend_branch_command_snapshots.ts',
      '20260921200000_access_create_admin_invitations.ts',
      '20260921201000_access_enable_admin_role_lifecycle.ts',
      '20260921202000_access_enforce_global_pending_invitation_email.ts',
    ],
  );
  const migration = await readFile(migrationPath, 'utf8');
  for (const forbidden of [
    'insertInto',
    'updateTable',
    'deleteFrom',
    'mergeInto',
    '.cascade(',
    'sql`',
  ]) {
    assert.equal(migration.includes(forbidden), false);
  }
});

test('database schema types are immutable and require externally supplied identity and time', async () => {
  const schema = await readFile(
    'src/infrastructure/database/database-types.ts',
    'utf8',
  );
  assert.match(schema, /type ImmutableColumn<T> = ColumnType<T, T, never>/u);
  assert.match(schema, /readonly tenant_id: ImmutableColumn<string>/u);
  assert.match(schema, /readonly branch_id: ImmutableColumn<string>/u);
  assert.match(schema, /readonly time_zone: MutableColumn<string>/u);
  assert.match(schema, /readonly active: DefaultedMutableColumn<boolean>/u);
  assert.match(schema, /readonly revoked_at: ImmutableColumn<Date \| null>/u);
  assert.match(schema, /readonly created_at: ImmutableColumn<Date>/u);
  assert.doesNotMatch(schema, /Generated/u);
});
