import { randomUUID } from 'node:crypto';
import { catalogFieldPolicyRegistry, catalogFieldPolicySchemaVersion, productDefaultCatalogFieldPolicyLevels, validateCatalogFieldPolicyLevels } from '../domain/catalog-field-policy.js';
import type { CatalogFieldPolicyConfigurationContext, CatalogFieldPolicyRecord, CatalogFieldPolicyRepositoryPort, CatalogFieldPolicyScope } from './ports/catalog-field-policy-repository.port.js';
export { CatalogFieldPolicyAuthorizationChangedError, CatalogFieldPolicyConcurrencyConflictError } from './ports/catalog-field-policy-repository.port.js';

export class CatalogFieldPolicyInputError extends Error { constructor(readonly parameter: string) { super('Catalog field policy input is invalid.'); this.name = 'CatalogFieldPolicyInputError'; } }
export type CatalogFieldPolicyProjection = CatalogFieldPolicyRecord & Readonly<{ source: 'product-default' | 'tenant'; registry: typeof catalogFieldPolicyRegistry }>;
function exactObject(value: unknown, keys: readonly string[]): Readonly<Record<string, unknown>> { if (typeof value !== 'object' || value === null || Array.isArray(value)) throw new CatalogFieldPolicyInputError('payload'); const input = value as Readonly<Record<string, unknown>>; if (Object.keys(input).some((key) => !keys.includes(key))) throw new CatalogFieldPolicyInputError('payload'); return input; }
function expectedVersion(value: unknown): number { if (!Number.isInteger(value) || Number(value) < 0) throw new CatalogFieldPolicyInputError('expectedVersion'); return Number(value); }
export class CatalogFieldPolicyService {
  constructor(private readonly repository: CatalogFieldPolicyRepositoryPort, private readonly now: () => Date = () => new Date(), private readonly createId: () => string = randomUUID) {}
  async effective(scope: CatalogFieldPolicyScope): Promise<CatalogFieldPolicyProjection> { const stored = await this.repository.readCatalogFieldPolicy(scope); const record = stored ?? Object.freeze({ schemaVersion: catalogFieldPolicySchemaVersion, policyVersion: 0, fieldLevels: productDefaultCatalogFieldPolicyLevels(), updatedAt: null }); return Object.freeze({ ...record, fieldLevels: validateCatalogFieldPolicyLevels(record.fieldLevels), source: stored ? 'tenant' : 'product-default', registry: catalogFieldPolicyRegistry }); }
  async update(context: CatalogFieldPolicyConfigurationContext, value: unknown): Promise<CatalogFieldPolicyProjection> { const input = exactObject(value, ['expectedVersion', 'fieldLevels']); const current = await this.effective(context); let fieldLevels; try { fieldLevels = validateCatalogFieldPolicyLevels(input.fieldLevels); } catch { throw new CatalogFieldPolicyInputError('fieldLevels'); } const result = await this.repository.changeCatalogFieldPolicy(context, { expectedVersion: expectedVersion(input.expectedVersion), schemaVersion: catalogFieldPolicySchemaVersion, previousFieldLevels: current.fieldLevels, fieldLevels, action: 'catalog_field_policy.updated', correlationId: this.createId(), occurredAt: this.now() }); return Object.freeze({ ...result, source: 'tenant', registry: catalogFieldPolicyRegistry }); }
  async reset(context: CatalogFieldPolicyConfigurationContext, value: unknown): Promise<CatalogFieldPolicyProjection> { const input = exactObject(value, ['expectedVersion']); const current = await this.effective(context); const result = await this.repository.changeCatalogFieldPolicy(context, { expectedVersion: expectedVersion(input.expectedVersion), schemaVersion: catalogFieldPolicySchemaVersion, previousFieldLevels: current.fieldLevels, fieldLevels: productDefaultCatalogFieldPolicyLevels(), action: 'catalog_field_policy.reset', correlationId: this.createId(), occurredAt: this.now() }); return Object.freeze({ ...result, source: 'tenant', registry: catalogFieldPolicyRegistry }); }
}
